export const mockGradeSubmissions = [
  {
    id: 1,
    teacher: 'Ms. Santos, Maria',
    subject: 'Mathematics',
    gradeLevel: 'Grade 1',
    section: 'Morning',
    studentCount: 25,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q1',
    status: 'Submitted',
    submittedDate: '2024-03-20'
  },
  {
    id: 2,
    teacher: 'Mr. Cruz, Roberto',
    subject: 'English',
    gradeLevel: 'Grade 1',
    section: 'Afternoon',
    studentCount: 23,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q1',
    status: 'Approved',
    submittedDate: '2024-03-18'
  },
  {
    id: 3,
    teacher: 'Ms. Reyes, Angela',
    subject: 'Science',
    gradeLevel: 'Grade 2',
    section: 'Morning',
    studentCount: 28,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q1',
    status: 'Pending',
    submittedDate: '2024-03-22'
  },
  {
    id: 4,
    teacher: 'Mr. Tan, Michael',
    subject: 'Filipino',
    gradeLevel: 'Grade 2',
    section: 'Afternoon',
    studentCount: 26,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q1',
    status: 'Submitted',
    submittedDate: '2024-03-21'
  },
  {
    id: 5,
    teacher: 'Ms. Lim, Jennifer',
    subject: 'Araling Panlipunan',
    gradeLevel: 'Grade 3',
    section: 'Morning',
    studentCount: 24,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q1',
    status: 'Rejected',
    submittedDate: '2024-03-19'
  },
  {
    id: 6,
    teacher: 'Mr. Sy, David',
    subject: 'MAPEH',
    gradeLevel: 'Grade 3',
    section: 'Afternoon',
    studentCount: 22,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q2',
    status: 'Submitted',
    submittedDate: '2024-03-20'
  },
  {
    id: 7,
    teacher: 'Ms. Ong, Richard',
    subject: 'Mathematics',
    gradeLevel: 'Grade 4',
    section: 'Morning',
    studentCount: 27,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q2',
    status: 'Approved',
    submittedDate: '2024-03-17'
  },
  {
    id: 8,
    teacher: 'Mr. Dela Cruz, Lorna',
    subject: 'English',
    gradeLevel: 'Grade 4',
    section: 'Afternoon',
    studentCount: 25,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q2',
    status: 'Pending',
    submittedDate: '2024-03-23'
  },
  {
    id: 9,
    teacher: 'Ms. Garcia, Anna',
    subject: 'Science',
    gradeLevel: 'Grade 5',
    section: 'Morning',
    studentCount: 30,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q2',
    status: 'Submitted',
    submittedDate: '2024-03-21'
  },
  {
    id: 10,
    teacher: 'Mr. Fernandez, Ramon',
    subject: 'Filipino',
    gradeLevel: 'Grade 5',
    section: 'Afternoon',
    studentCount: 28,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q2',
    status: 'Approved',
    submittedDate: '2024-03-18'
  },
  {
    id: 11,
    teacher: 'Ms. Torres, Elena',
    subject: 'Mathematics',
    gradeLevel: 'Grade 6',
    section: 'Morning',
    studentCount: 32,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q3',
    status: 'Submitted',
    submittedDate: '2024-03-20'
  },
  {
    id: 12,
    teacher: 'Mr. Ramos, Jose',
    subject: 'English',
    gradeLevel: 'Grade 6',
    section: 'Afternoon',
    studentCount: 30,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q3',
    status: 'Pending',
    submittedDate: '2024-03-22'
  },
  {
    id: 13,
    teacher: 'Ms. Lee, Katherine',
    subject: 'Science',
    gradeLevel: 'Grade 1',
    section: 'Morning',
    studentCount: 25,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q3',
    status: 'Submitted',
    submittedDate: '2024-03-19'
  },
  {
    id: 14,
    teacher: 'Mr. Garcia, Steven',
    subject: 'Filipino',
    gradeLevel: 'Grade 2',
    section: 'Afternoon',
    studentCount: 26,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q3',
    status: 'Approved',
    submittedDate: '2024-03-17'
  },
  {
    id: 15,
    teacher: 'Ms. Martinez, Sofia',
    subject: 'MAPEH',
    gradeLevel: 'Grade 3',
    section: 'Morning',
    studentCount: 24,
    enrollmentDate: '2024-01-15',
    gradingPeriod: 'Q4',
    status: 'Submitted',
    submittedDate: '2024-03-21'
  }
];