export const mockFinancialHolds = [
  {
    id: 1,
    studentId: '2024-00123',
    name: 'Althea Rodriguez',
    gradeLevel: 'Grade 1',
    section: 'Morning',
    outstandingBalance: '₱5,250.00',
    examPeriod: 'Midterm',
    holdStatus: 'Active',
    parentGuardian: 'Maricel Rodriguez',
    contact: '+63 912 345 6789'
  },
  {
    id: 2,
    studentId: '2024-00124', 
    name: 'Brandon Cruz',
    gradeLevel: 'Grade 1',
    section: 'Afternoon',
    outstandingBalance: '₱3,800.00',
    examPeriod: 'Final',
    holdStatus: 'Active',
    parentGuardian: 'Roberto Cruz',
    contact: '+63 917 234 5678'
  },
  {
    id: 3,
    studentId: '2024-00125',
    name: 'Chloe Tan',
    gradeLevel: 'Grade 2',
    section: 'Morning',
    outstandingBalance: '₱2,150.00',
    examPeriod: 'Midterm',
    holdStatus: 'Pending',
    parentGuardian: 'Michael Tan',
    contact: '+63 918 345 6789'
  },
  {
    id: 4,
    studentId: '2024-00126',
    name: 'Daniel Lim',
    gradeLevel: 'Grade 1',
    section: 'Morning',
    outstandingBalance: '₱0.00',
    examPeriod: 'Final',
    holdStatus: 'Cleared',
    parentGuardian: 'Jennifer Lim',
    contact: '+63 919 456 7890'
  },
  {
    id: 5,
    studentId: '2024-00127',
    name: 'Ella Sy',
    gradeLevel: 'Grade 3',
    section: 'Afternoon',
    outstandingBalance: '₱7,500.00',
    examPeriod: 'Special Exam',
    holdStatus: 'Active',
    parentGuardian: 'David Sy',
    contact: '+63 920 567 8901'
  },
  {
    id: 6,
    studentId: '2024-00128',
    name: 'Francisco Reyes',
    gradeLevel: 'Grade 2',
    section: 'Afternoon',
    outstandingBalance: '₱1,200.00',
    examPeriod: 'Midterm',
    holdStatus: 'Active',
    parentGuardian: 'Angela Reyes',
    contact: '+63 921 678 9012'
  },
  {
    id: 7,
    studentId: '2024-00129',
    name: 'Gabriella Ong',
    gradeLevel: 'Grade 1',
    section: 'Morning',
    outstandingBalance: '₱0.00',
    examPeriod: 'Final',
    holdStatus: 'Cleared',
    parentGuardian: 'Richard Ong',
    contact: '+63 922 789 0123'
  },
  {
    id: 8,
    studentId: '2024-00130',
    name: 'Hector dela Cruz',
    gradeLevel: 'Grade 2',
    section: 'Morning',
    outstandingBalance: '₱4,300.00',
    examPeriod: 'Final',
    holdStatus: 'Active',
    parentGuardian: 'Lorna dela Cruz',
    contact: '+63 923 890 1234'
  },
  {
    id: 9,
    studentId: '2024-00131',
    name: 'Isabella Santos',
    gradeLevel: 'Grade 3',
    section: 'Morning',
    outstandingBalance: '₱6,750.00',
    examPeriod: 'Midterm',
    holdStatus: 'Pending',
    parentGuardian: 'Carlos Santos',
    contact: '+63 924 901 2345'
  },
  {
    id: 10,
    studentId: '2024-00132',
    name: 'Jacob Tan',
    gradeLevel: 'Grade 2',
    section: 'Afternoon',
    outstandingBalance: '₱0.00',
    examPeriod: 'Special Exam',
    holdStatus: 'Cleared',
    parentGuardian: 'Maria Tan',
    contact: '+63 925 012 3456'
  },
  {
    id: 11,
    studentId: '2024-00133',
    name: 'Katherine Lee',
    gradeLevel: 'Grade 3',
    section: 'Morning',
    outstandingBalance: '₱3,200.00',
    examPeriod: 'Final',
    holdStatus: 'Active',
    parentGuardian: 'Steven Lee',
    contact: '+63 926 123 4567'
  },
  {
    id: 12,
    studentId: '2024-00134',
    name: 'Liam Garcia',
    gradeLevel: 'Grade 1',
    section: 'Afternoon',
    outstandingBalance: '₱8,100.00',
    examPeriod: 'Midterm',
    holdStatus: 'Active',
    parentGuardian: 'Anna Garcia',
    contact: '+63 927 234 5678'
  },
  {
    id: 13,
    studentId: '2024-00135',
    name: 'Mia Fernandez',
    gradeLevel: 'Grade 2',
    section: 'Morning',
    outstandingBalance: '₱0.00',
    examPeriod: 'Final',
    holdStatus: 'Cleared',
    parentGuardian: 'Ramon Fernandez',
    contact: '+63 928 345 6789'
  },
  {
    id: 14,
    studentId: '2024-00136',
    name: 'Nathan Torres',
    gradeLevel: 'Grade 3',
    section: 'Afternoon',
    outstandingBalance: '₱2,800.00',
    examPeriod: 'Special Exam',
    holdStatus: 'Pending',
    parentGuardian: 'Elena Torres',
    contact: '+63 929 456 7890'
  },
  {
    id: 15,
    studentId: '2024-00137',
    name: 'Olivia Ramos',
    gradeLevel: 'Grade 1',
    section: 'Morning',
    outstandingBalance: '₱5,600.00',
    examPeriod: 'Midterm',
    holdStatus: 'Active',
    parentGuardian: 'Jose Ramos',
    contact: '+63 930 567 8901'
  }
];